### ISSUE TITLE
Graph in Overview Section

### ISSUE THREAD

**Issue by vvlabs** [lannister-capital/lannister-app#1]
The graph seems to be malfunctioning when I enter numbers in. I entered 99999 and that appeared smaller than your 20,000 examples. 

Also, I cannot delete your example holdings, and the recommendations and settings page do nothing.

**Comment by alvesjtiago** [comment]
Thanks for opening up this issue but this project is still under development. The currently released version is the iOS one and can be found at https://github.com/lannister-capital/lannister-ios.

Thank you
