### ISSUE TITLE
Automatically update the corresponding price of bitcoin and ether

### ISSUE THREAD

**Issue by alvesjtiago** [lannister-capital/lannister-app#11]
Integrate with an API that fetches and updates the corresponding value of bitcoin and ether relative to euro locally. Conversions with other currencies are made by a second step.

**Comment by clarencejychan** [comment]
I'm looking at `https://www.cryptonator.com/api` as a potential candidate that can provide ETH/BTC price in multiple currencies. I think we'd be limited to API's that don't require key's since we don't really have a back-end so we have no where to store them securely.

**Comment by alvesjtiago** [comment]
That's the same one we're using on the iOS app so it was also our first option. I forgot to add it to this issue. Thanks for researching again @clarencejychan, it gives us even more confidence knowing that we've reached the same conclusion 😊

Maybe in the future we'll be able to either run our own API or fallback to other API's not to be dependent on a single one.

**Comment by clarencejychan** [comment]
I'd like to tackle this one if possible!

**Comment by alvesjtiago** [comment]
Of course @clarencejychan, assigning you!
