### ISSUE TITLE
Add global currency settings

### ISSUE THREAD

**Issue by alvesjtiago** [lannister-capital/lannister-app#17]
Add global currency settings preference stored locally to display holdings value via the `euro_rate` conversion.

**Comment by alvesjtiago** [comment]
@andresousa how is this information being stored on the iOS app? Only locally or are you syncing with the db as well?

**Comment by andresousa** [comment]
Only locally. But we can add it as a separate table on the local db. Open for discussion.

**Comment by alvesjtiago** [comment]
Got it. Let's keep it locally for now and discuss syncing in the future.
