### ISSUE TITLE
Export data

### ISSUE THREAD

**Issue by alvesjtiago** [lannister-capital/lannister-app#26]
Exporting data should allow for the first version to create a CSV version of the data: a CSV with all the holdings with the corresponding data and include the converted values to the global currency as well.

**Comment by clarencejychan** [comment]
Do we expect the csv to contain what the global currency state is as well?

**Comment by alvesjtiago** [comment]
We still don’t have a csv structure defined but I think for the first version a total value and each holding listed is perfect.

**Comment by andresousa** [comment]
Why is this issue closed @alvesjtiago? Should we discard it for the 1st version? If it's the case, the "Export Data" option should be removed from the Settings screen.

**Comment by alvesjtiago** [comment]
This was already implemented by @clarencejychan. It's not working for you?

**Comment by clarencejychan** [comment]
@alvesjtiago @andresousa, I just ran the latest master branch and I'm still able to generate a csv file. Tested on google chrome.

**Comment by andresousa** [comment]
Right! It works on Chrome. It doesn't work on Safari.

**Comment by alvesjtiago** [comment]
Reopening this issue. Do you mind taking a look @clarencejychan? 😊

**Comment by clarencejychan** [comment]
I’ll take a look as soon as I get home! Thanks.

**Comment by alvesjtiago** [comment]
Thank you @clarencejychan 🙏
