### ISSUE TITLE
Display percentage of each holding on chart

### ISSUE THREAD

**Issue by alvesjtiago** [lannister-capital/lannister-app#27]
The pie chart should display the percentage that each holding contributes to the whole.

**Comment by clarencejychan** [comment]
@alvesjtiago mind if I take on the percentage issues?

**Comment by alvesjtiago** [comment]
Of course @clarencejychan, feel free to tackle this issue! Assigning you.

**Comment by clarencejychan** [comment]
I checked the figma, but couldn't see anything with the percent except for the percent sign in the middle. How do we actually want to show the percentage, right next to the amount, or when they click on somewhere?

**Comment by alvesjtiago** [comment]
Can we start by replacing the numbers on the graph with the percentage they represent? I believe it's more informative. If you have any suggestions to modify the pie chart, do let us know. We're open to all feedback 😊

**Comment by clarencejychan** [comment]
So I took a look at the iOS version and the figma and they both have the percentage in the middle. Are we going to be abandoning that design? Originally I thought about showing the percentage on hover of each section or something similar to that.

**Comment by alvesjtiago** [comment]
Percentage on hover or just having the percentage display for each section on the graph sounds great. We're just aiming at releasing the first basic useful version and then we can re-focus on the design and new features.
