### ISSUE TITLE
Add logo at the top left corner

### ISSUE THREAD

**Issue by alvesjtiago** [lannister-capital/lannister-app#3]
![Overview](https://user-images.githubusercontent.com/407470/59518238-2dcec700-8ebd-11e9-8b05-80286832e538.png)

**Comment by clarencejychan** [comment]
Hi there, I was looking to do this first quick issue but i was wondering if you have the asset for the lion head available or if you'd rather just have a placeholder there for now.

**Comment by alvesjtiago** [comment]
Thank you @clarencejychan. I will add this information to the readme but you can access the figma with the design directly at https://www.figma.com/file/TPuNDdmafH54uRfWCBHccMKQ/Lannister.

I'm also attaching the logo export in png here (since I can't add an svg file) to this comment so you can use it right away.

![gray-logo](https://user-images.githubusercontent.com/407470/59555775-8b434080-8faf-11e9-90fe-f4e4912df8ab.png)
<img width="55" alt="gray-logo@2x" src="https://user-images.githubusercontent.com/407470/59555776-8bdbd700-8faf-11e9-9c6e-24ebbe4189d3.png">
