### ISSUE TITLE
Don't allow negative values when creating holding

### ISSUE THREAD

**Issue by andresousa** [lannister-capital/lannister-app#46]
<img width="1280" alt="Screenshot 2019-07-24 at 09 17 51" src="https://user-images.githubusercontent.com/1278551/61776988-050eeb00-adf4-11e9-8362-bca71e3f2906.png">
<img width="1280" alt="Screenshot 2019-07-24 at 09 18 05" src="https://user-images.githubusercontent.com/1278551/61776989-050eeb00-adf4-11e9-9c2c-2de466eb3e55.png">

**Comment by andresousa** [comment]
<img width="1280" alt="Screenshot 2019-07-24 at 09 19 05" src="https://user-images.githubusercontent.com/1278551/61777021-1821bb00-adf4-11e9-92e3-b0a2346a1f75.png">

**Comment by clarencejychan** [comment]
@alvesjtiago I can also take this one on! Thanks.

**Comment by alvesjtiago** [comment]
Of course, assigning it to you!
