### ISSUE TITLE
Implement empty state when portfolio doesn't have any holdings

### ISSUE THREAD

**Issue by andresousa** [lannister-capital/lannister-app#47]
<img width="1280" alt="Screenshot 2019-07-24 at 09 22 12" src="https://user-images.githubusercontent.com/1278551/61777529-f8d75d80-adf4-11e9-96b4-6908d796c920.png">

**Comment by andresousa** [comment]
![Simulator Screen Shot - iPhone Xs - 2019-07-24 at 09 24 38](https://user-images.githubusercontent.com/1278551/61777591-14daff00-adf5-11e9-9083-2b51c75dc9c7.png)

**Comment by clarencejychan** [comment]
@alvesjtiago I could take this one on! I'll just assume since we don't have designs for this state on Figma, it should look somewhat consistent with the iOS version.

**Comment by alvesjtiago** [comment]
Exactly @clarencejychan, we should probably have a button under holdings to add a new holding and display an empty graph. Let me get something design wise before we start implementing this one and I'll ping you.

**Comment by clarencejychan** [comment]
@alvesjtiago sounds good, let me know whenever we have something for the design.
