### ISSUE TITLE
List holdings on holdings view

### ISSUE THREAD

**Issue by alvesjtiago** [lannister-capital/lannister-app#5]
![Holdings](https://user-images.githubusercontent.com/407470/59518618-e39a1580-8ebd-11e9-919c-ad8a5374f503.png)

**Comment by clarencejychan** [comment]
From what I can see, this looks like it's been implemented already.

**Comment by alvesjtiago** [comment]
That's true @clarencejychan. The holdings rows are missing some info but that should be handled on a separate ticket. Closing this one.
