### ISSUE TITLE
Chart labels don't appear

### ISSUE THREAD

**Issue by alvesjtiago** [lannister-capital/lannister-app#50]
When opening the dashboard or any other view that contains a chart, if you hover it before it is finished loading it will not display the labels 👇

<img width="449" alt="Screen Shot 2019-08-01 at 7 14 24 PM" src="https://user-images.githubusercontent.com/407470/62335256-c4b50a00-b490-11e9-82dc-02498724ab62.png">

**Comment by clarencejychan** [comment]
I can take this on since I implemented the labels originally. Interesting bug though

**Comment by alvesjtiago** [comment]
Thanks @clarencejychan! It is an interesting bug indeed...

**Comment by clarencejychan** [comment]
@alvesjtiago do you have any repro steps or some sorta gif with console output you could show me? I tried to reproduce this on both safari and chrome and I can't do so.

**Comment by alvesjtiago** [comment]
Here it is a gif @clarencejychan 👇 let me know if you still can't reproduce it.

![Screen Recording 2019-08-06 at 23 26 25](https://user-images.githubusercontent.com/407470/62590451-c9b7f600-b8a2-11e9-9fb2-160fb0ba058e.gif)
