### ISSUE TITLE
Create transaction

### ISSUE THREAD

**Issue by alvesjtiago** [lannister-capital/lannister-app#8]
Add the ability to create a transaction via modal by selecting name, type and value. Follow the same data structure as iOS.
![Create Transaction](https://user-images.githubusercontent.com/407470/59518803-5f945d80-8ebe-11e9-96ce-b6f35b55c371.png)

**Comment by alvesjtiago** [comment]
@andresousa to keep it documented, do you mind adding here the data structure for a transaction? Thanks!

**Comment by andresousa** [comment]
id
name
type
value
relationship: holding

**Comment by clarencejychan** [comment]
From what I can see this also looks like it's been implemented already.

**Comment by alvesjtiago** [comment]
Hi @clarencejychan, not really. What has been implemented is the creation of holdings, not transactions.

**Comment by alvesjtiago** [comment]
Only missing adding the ability to select between credit or debit.

**Comment by alvesjtiago** [comment]
Done 👌

<img width="1680" alt="Screenshot 2019-06-22 at 20 41 36" src="https://user-images.githubusercontent.com/407470/59968216-28612480-952e-11e9-8ac3-2b3bfcb0bf8b.png">
